---
ubuntu_openvpn_pkgs:
  - openvpn
  - netfilter-persistent
  - iptables-persistent
  - udev
  - dnsmasq

openvpn_key_country:  "DE"
openvpn_key_province: "Bavaria"
openvpn_key_city: "Munich"
openvpn_key_org: "ACME"
openvpn_key_ou: "IT Department"
openvpn_days_valid: "1825"
openssl_request_subject: "/C={{ openvpn_key_country }}/ST={{ openvpn_key_province }}/L={{ openvpn_key_city }}/O={{ openvpn_key_org }}/OU={{ openvpn_key_ou }}"
openvpn_key_size: "2048"
openvpn_cipher: "BF-CBC"
openvpn_auth_digest: "SHA1"
openvpn_path: "/etc/openvpn"
openvpn_ca: "{{ openvpn_path }}/ca"
openvpn_dhparam: "{{ openvpn_path }}/dh{{ openvpn_key_size }}.pem"
openvpn_hmac_firewall: "{{ openvpn_path }}/ta.key"
openvpn_server: "acme.local"
openvpn_port: "1194"
openvpn_protocol: "udp"

openvpn_network: "10.254.254.0"

private_networks:
  - 10.10.0.0

iptables_openvpn_rules:
  - /sbin/iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
  - /sbin/iptables -A FORWARD -s {{ openvpn_network }}/24 -j ACCEPT
  - /sbin/iptables -A FORWARD -j REJECT
  - /sbin/iptables -t nat -A POSTROUTING -s {{ openvpn_network }}/24 -o {{ ansible_default_ipv4.interface }} -j MASQUERADE

openvpn_clients:
  - client-01
  - client-02
  - client-03
