---
- name: Ping Windows
  win_ping:
  tags: win

- name: run ipconfig
  raw: ipconfig
  register: ipconfig
- debug: var=ipconfig

 # Do this for all Windows 10 systems
- name: Enable Terminal Server
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  with_items:
  - { name: fDenyTSConnections,    data: 0 }
  - { name: fSingleSessionPerUser, data: 0 }

- name: Set RDP/tcp settings
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  with_items:
  - { name: PortNumber,         data: 3389 }
  - { name: SecurityLayer,      data: 1 }
  - { name: UserAuthentication, data: 0 }
  - { name: Shadow,             data: 1 }

- name: Configure RDP firewall rule
  win_firewall_rule:
    name: ARemote Desktop - User Mode (TCP-In)
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
